# Generated by Django 3.1.7 on 2021-02-24 18:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercyclecomponent',
            name='flows_to_set',
            field=models.ManyToManyField(help_text='The set of water cycle components to which water flows.', related_name='flows_from_set', through='greenhouse.WaterCycleFlowsTo', to='greenhouse.WaterCycleComponent'),
        ),
        migrations.CreateModel(
            name='WaterCycleLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('since', models.DateTimeField(default=datetime.datetime.now, help_text='The time from when a water cycle component was part of a water cycle.')),
                ('until', models.DateTimeField(blank=True, help_text='The time until when a water cycle component was part of a water cycle.', null=True)),
                ('water_cycle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_cycle_component_edges', to='greenhouse.watercycle')),
                ('water_cycle_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_cycle_edges', to='greenhouse.watercyclecomponent')),
            ],
        ),
        migrations.AddField(
            model_name='watercyclecomponent',
            name='water_cycle_log_set',
            field=models.ManyToManyField(help_text='A log of when this water cycle component was connected to which water cycle.', related_name='water_cycle_component_logs', through='greenhouse.WaterCycleLog', to='greenhouse.WaterCycle'),
        ),
    ]
