# Generated by Django 3.1.7 on 2021-02-28 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0002_auto_20210224_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watercyclecomponent',
            name='water_cycle',
            field=models.ForeignKey(blank=True, help_text='To which water cycle this site entity belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_cycle_component', to='greenhouse.watercycle'),
        ),
        migrations.AlterField(
            model_name='watercyclecomponent',
            name='water_cycle_log_set',
            field=models.ManyToManyField(help_text='A log of when this water cycle component was connected to which water cycle.', related_name='water_cycle_component_log_set', through='greenhouse.WaterCycleLog', to='greenhouse.WaterCycle'),
        ),
        migrations.AlterField(
            model_name='watercyclelog',
            name='water_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_cycle_component_log_edges', to='greenhouse.watercycle'),
        ),
        migrations.AlterField(
            model_name='watercyclelog',
            name='water_cycle_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_cycle_log_edges', to='greenhouse.watercyclecomponent'),
        ),
    ]
