# Generated by Django 3.1.7 on 2021-03-30 13:59

from django.db import migrations, models
import iot.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0005_plantimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(editable=False, help_text='The image of a plant.', storage=iot.storage_backends.PrivateMediaStorage, upload_to=''),
        ),
    ]
