# Generated by Django 3.1.7 on 2021-04-05 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_datapointtype_created_by'),
        ('greenhouse', '0006_auto_20210330_1359'),
    ]

    operations = [
        migrations.AddField(
            model_name='watercycle',
            name='site',
            field=models.ForeignKey(default='00000000-0000-0000-0000-000000000000', help_text='To which site it belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='water_cycle_set', to='iot.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='watercycleflowsto',
            name='flows_from',
            field=models.ForeignKey(help_text='From which water cycle the water flows.', on_delete=django.db.models.deletion.CASCADE, related_name='flows_to_edges', to='greenhouse.watercyclecomponent'),
        ),
        migrations.AlterField(
            model_name='watercycleflowsto',
            name='flows_to',
            field=models.ForeignKey(help_text='To which water cycle the water flows.', on_delete=django.db.models.deletion.CASCADE, related_name='flows_from_edges', to='greenhouse.watercyclecomponent'),
        ),
        migrations.AlterField(
            model_name='watercyclelog',
            name='water_cycle',
            field=models.ForeignKey(help_text='To which water cycle it was assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='water_cycle_component_log_edges', to='greenhouse.watercycle'),
        ),
        migrations.AlterField(
            model_name='watercyclelog',
            name='water_cycle_component',
            field=models.ForeignKey(help_text='Which water cycle component was logged.', on_delete=django.db.models.deletion.CASCADE, related_name='water_cycle_log_edges', to='greenhouse.watercyclecomponent'),
        ),
    ]
