# Generated by Django 3.1.8 on 2021-04-14 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0007_auto_20210405_1939'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='plant',
            field=models.ForeignKey(help_text='The primary plant in the image.', on_delete=django.db.models.deletion.CASCADE, related_name='plant_image_set', to='greenhouse.plantcomponent'),
        ),
    ]
