# Generated by Django 3.1.10 on 2021-05-06 20:23

from django.db import migrations, models
import greenhouse.models.plant_image
import iot.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('greenhouse', '0008_auto_20210414_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantimage',
            name='image',
            field=models.ImageField(editable=False, help_text='The image of a plant.', storage=iot.storage_backends.PrivateMediaStorage, upload_to=greenhouse.models.plant_image.PlantImageManager.generate_path),
        ),
    ]
