# Generated by Django 2.1.5 on 2019-02-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_profile_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='full_name',
            field=models.CharField(blank=True, help_text="Stores a user's full name. Useful due to significant variations in local naming schemes.", max_length=150, verbose_name='full name'),
        ),
    ]
