version: "3.3"

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    logging:
      driver: "json-file"
      options:
          max-file: "5"
          max-size: "10m"
    ports:
      - "1.1.1.1:80:80"
      - "1.1.1.1:443:443"
    volumes:
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "./dynamic_conf.yml:/etc/traefik/dynamic_conf.yml"
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - default

# Make the externally created network "gateway" available as network "default"
networks:
  default:
    external: 
      name: gateway
