"""empty message

Revision ID: 7e08af6a564a
Revises: d79a8dc20bc7
Create Date: 2018-01-21 12:57:17.598768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e08af6a564a'
down_revision = 'd79a8dc20bc7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('disallow_grant_type', sa.String(length=20), nullable=True))
    op.drop_constraint('client_user_id_fkey', 'client', type_='foreignkey')
    op.drop_column('client', 'user_id')
    op.drop_column('client', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('client', sa.Column('description', sa.VARCHAR(length=400), autoincrement=False, nullable=True))
    op.add_column('client', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('client_user_id_fkey', 'client', 'users', ['user_id'], ['id'])
    op.drop_column('client', 'disallow_grant_type')
    # ### end Alembic commands ###
