# Generated by Django 3.0.5 on 2020-04-08 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mqttmessage',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AlterUniqueTogether(
            name='mqttmessage',
            unique_together={('created_at', 'coordinator')},
        ),
    ]
