# Generated by Django 3.0.5 on 2020-04-12 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0002_auto_20200408_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coordinator',
            name='site',
            field=models.ForeignKey(blank=True, help_text='The site to which the coordinator belongs.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='farms.Site'),
        ),
    ]
