# Generated by Django 3.0.5 on 2020-05-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0004_auto_20200414_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='channel_name',
            field=models.CharField(default='', help_text='The channel name of the connected WebSocket.', max_length=64),
        ),
    ]
