# Generated by Django 3.0.5 on 2020-05-05 10:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0005_coordinator_channel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinator',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user account with which the coordinator can log in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
