# Generated by Django 3.0.5 on 2020-06-26 16:22

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0006_coordinator_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The datetime when the message was received')),
                ('message', django.contrib.postgres.fields.jsonb.JSONField()),
                ('controller', models.ForeignKey(help_text='The controller associated with the message.', on_delete=django.db.models.deletion.CASCADE, to='farms.Controller')),
            ],
            options={
                'unique_together': {('created_at', 'controller')},
            },
        ),
    ]
