# Generated by Django 3.0.5 on 2020-06-26 16:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('farms', '0007_controllermessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='controller',
            name='channel_name',
            field=models.CharField(default='', help_text='The channel name of the connected WebSocket.', max_length=64),
        ),
        migrations.AddField(
            model_name='controller',
            name='user',
            field=models.ForeignKey(blank=True, help_text='The user account with which the coordinator can log in.', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
