# Generated by Django 3.0.5 on 2020-08-22 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0008_auto_20200626_1833'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='farms.Controller')),
            ],
        ),
    ]
