# Generated by Django 3.0.9 on 2020-08-30 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0010_auto_20200830_2109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='channel_name',
            field=models.CharField(default='', help_text='The channel name of the connected WebSocket.', max_length=128),
        ),
        migrations.AlterField(
            model_name='controllertoken',
            name='key',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
    ]
