# Generated by Django 3.0.10 on 2020-09-19 22:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0011_auto_20200830_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controller',
            name='channel_name',
            field=models.CharField(blank=True, default='', help_text='The channel name of the connected WebSocket.', max_length=128),
        ),
        migrations.AlterField(
            model_name='controller',
            name='coordinator',
            field=models.ForeignKey(blank=True, help_text='The coordinator with which the controller is connected to.', null=True, on_delete=django.db.models.deletion.CASCADE, to='farms.Coordinator'),
        ),
    ]
