# Generated by Django 3.1.2 on 2020-10-09 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0015_auto_20201005_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControllerAuthToken',
            fields=[
                ('key', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('controller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auth_token', to='farms.controllercomponent')),
            ],
        ),
        migrations.DeleteModel(
            name='ControllerToken',
        ),
    ]
