# Generated by Django 3.1.2 on 2020-10-26 18:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0017_auto_20201011_1338'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllermessage',
            name='request_id',
            field=models.CharField(default='', help_text='The ID of the request, to enable tracking requests', max_length=255),
        ),
        migrations.AlterField(
            model_name='peripheralcomponent',
            name='config',
            field=models.JSONField(help_text='The config sent to the controller to perform setup.'),
        ),
        migrations.CreateModel(
            name='ControllerTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('task_type', models.CharField(choices=[('InvalidTask', 'Invalid task'), ('AlertSensor', 'Alert sensor'), ('PollSensor', 'Poll sensor'), ('ReadSensor', 'Read sensor'), ('SetLight', 'Set light'), ('WriteActuator', 'Write actuator')], help_text='The type of the task on the controller', max_length=64)),
                ('state', models.CharField(choices=[('starting', 'Starting'), ('running', 'Running'), ('stopping', 'Stopping'), ('failed', 'Failed'), ('stopped', 'Stopped')], help_text='The state of the controller task.', max_length=64)),
                ('parameters', models.JSONField(help_text='The construction parameters excl. UUID and type')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The datetime of creation.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The datetime of the last update.')),
                ('controller_component', models.ForeignKey(help_text='On which controller this task is executed.', on_delete=django.db.models.deletion.CASCADE, to='farms.controllercomponent')),
            ],
        ),
    ]
