# Generated by Django 3.1.2 on 2020-10-27 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0018_auto_20201026_1829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peripheralcomponent',
            name='component_type',
        ),
        migrations.AddField(
            model_name='peripheralcomponent',
            name='peripheral_type',
            field=models.CharField(choices=[('InvalidPeripheral', 'Invalid peripheral'), ('BME280', 'BME/BMP 280 sensor'), ('CapacitiveSensor', 'Capacitive sensor'), ('I2CAdapter', 'I2C Adapter'), ('LED', 'LED'), ('NeoPixel', 'NeoPixel array')], default='InvalidPeripheral', help_text='The type of this peripheral component.', max_length=64),
        ),
        migrations.AddField(
            model_name='peripheralcomponent',
            name='state',
            field=models.CharField(choices=[('adding', 'Adding'), ('added', 'Added'), ('failed', 'Failed'), ('removing', 'Removing'), ('removed', 'Removed')], default='failed', help_text='The state of the controller task.', max_length=64),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='PeripheralComponentType',
        ),
    ]
