# Generated by Django 3.1.2 on 2020-10-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0019_auto_20201027_0019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peripheralcomponent',
            name='config',
        ),
        migrations.AddField(
            model_name='peripheralcomponent',
            name='parameters',
            field=models.JSONField(default=list, help_text='Parameters for setup on controller excl. type'),
        ),
    ]
