# Generated by Django 3.1.3 on 2020-11-15 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0020_auto_20201027_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllertask',
            name='run_until',
            field=models.DateTimeField(blank=True, help_text='Until when the task should run.', null=True),
        ),
        migrations.AlterField(
            model_name='controllermessage',
            name='request_id',
            field=models.CharField(blank=True, default='', help_text='The ID of the request, to enable tracking requests', max_length=255),
        ),
        migrations.AlterField(
            model_name='controllertask',
            name='parameters',
            field=models.JSONField(blank=True, default=dict, help_text='The construction parameters excl. UUID and type'),
        ),
        migrations.AlterField(
            model_name='peripheralcomponent',
            name='parameters',
            field=models.JSONField(default=dict, help_text='Parameters for setup on controller excl. type'),
        ),
    ]
