# Generated by Django 3.1.3 on 2020-11-23 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0021_auto_20201115_1559'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='data_point_type',
            field=models.ForeignKey(help_text='The type of data recorded and its unit.', on_delete=django.db.models.deletion.CASCADE, related_name='data_point_set', to='farms.datapointtype'),
        ),
        migrations.AlterField(
            model_name='datapoint',
            name='peripheral_component',
            field=models.ForeignKey(help_text='The peripheral that generated the data point.', on_delete=django.db.models.deletion.CASCADE, related_name='data_point_set', to='farms.peripheralcomponent'),
        ),
        migrations.AlterField(
            model_name='peripheralcomponent',
            name='controller_component',
            field=models.ForeignKey(help_text='Which controller controls and is connected to this peripheral.', on_delete=django.db.models.deletion.CASCADE, related_name='peripheral_component_set', to='farms.controllercomponent'),
        ),
        migrations.AlterField(
            model_name='peripheralcomponent',
            name='site_entity',
            field=models.OneToOneField(help_text='Which site entity the component is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='peripheral_component', to='farms.siteentity'),
        ),
    ]
