# Generated by Django 3.1.3 on 2020-12-02 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0022_auto_20201123_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllertask',
            name='task_type',
            field=models.CharField(choices=[('InvalidType', 'Invalid type'), ('AlertSensor', 'Alert sensor'), ('PollSensor', 'Poll sensor'), ('ReadSensor', 'Read sensor'), ('SetLight', 'Set light'), ('WriteActuator', 'Write actuator')], help_text='The type of the task on the controller', max_length=64),
        ),
    ]
