# Generated by Django 3.1.3 on 2020-12-09 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0025_auto_20201209_1741'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeripheralDataPointType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_prefix', models.CharField(max_length=64)),
                ('data_point_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peripheral_edges', to='farms.datapointtype')),
                ('peripheral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='data_point_type_edges', to='farms.peripheralcomponent')),
            ],
        ),
        migrations.AddField(
            model_name='peripheralcomponent',
            name='data_point_type_set',
            field=models.ManyToManyField(related_name='peripheral_component_set', through='farms.PeripheralDataPointType', to='farms.DataPointType'),
        ),
    ]
