# Generated by Django 3.1.3 on 2020-12-09 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0026_auto_20201209_2225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='peripheralcomponent',
            old_name='parameters',
            new_name='other_parameters'
        ),
        migrations.AlterField(
            model_name='peripheraldatapointtype',
            name='data_point_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='peripheral_component_edges', to='farms.datapointtype'),
        ),
    ]
