# Generated by Django 3.1.3 on 2020-12-19 10:57

from django.db import migrations, models
import farms.models.peripheral


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0027_auto_20201209_2315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coordinator',
            name='site',
        ),
        migrations.RemoveField(
            model_name='coordinator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hydroponicsystem',
            name='site',
        ),
        migrations.AlterUniqueTogether(
            name='mqttmessage',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mqttmessage',
            name='controller',
        ),
        migrations.RemoveField(
            model_name='mqttmessage',
            name='coordinator',
        ),
        migrations.AlterField(
            model_name='peripheralcomponent',
            name='other_parameters',
            field=models.JSONField(blank=True, default=dict, help_text='Setup parameters excl. the data point type parameters.', validators=[farms.models.peripheral.validate_other_parameters]),
        ),
        migrations.AlterField(
            model_name='peripheraldatapointtype',
            name='parameter_prefix',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.DeleteModel(
            name='Controller',
        ),
        migrations.DeleteModel(
            name='Coordinator',
        ),
        migrations.DeleteModel(
            name='HydroponicSystem',
        ),
        migrations.DeleteModel(
            name='MqttMessage',
        ),
    ]
