# Generated by Django 3.1.4 on 2021-01-20 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0028_auto_20201219_1057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['-time']},
        ),
    ]
