# Generated by Django 3.1.4 on 2021-01-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0029_auto_20210120_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='controllertask',
            name='task_type',
            field=models.CharField(choices=[('InvalidType', 'Invalid type'), ('AlertSensor', 'Alert sensor'), ('PollSensor', 'Poll sensor'), ('ReadSensor', 'Read sensor'), ('SetRgbLed', 'Set RGB LED'), ('SetValue', 'Set value')], help_text='The type of the task on the controller', max_length=64),
        ),
        migrations.AlterField(
            model_name='peripheralcomponent',
            name='peripheral_type',
            field=models.CharField(choices=[('InvalidPeripheral', 'Invalid peripheral'), ('DigitalIn', 'Digital in'), ('DigitalOut', 'Digital out'), ('AnalogIn', 'Analog in'), ('AnalogOut', 'Analog out'), ('PWM', 'PWM'), ('BME280', 'BME/BMP 280 sensor'), ('CapacitiveSensor', 'Capacitive sensor'), ('I2CAdapter', 'I2C Adapter'), ('NeoPixel', 'NeoPixel array')], default='InvalidPeripheral', help_text='The type of this peripheral component.', max_length=64),
        ),
    ]
