"""Add InfluxDB access key

Revision ID: 6ccf284c4255
Revises: ed4062641439
Create Date: 2018-04-26 15:47:56.496394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6ccf284c4255'
down_revision = 'ed4062641439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('influx_dbs', sa.Column('missing_owner', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('influx_db_access_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'influx_db_access_key')
    op.drop_column('influx_dbs', 'missing_owner')
    # ### end Alembic commands ###
