# Generated by Django 3.1.7 on 2021-03-10 20:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import iot.models.controller


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0002_add_hypertable'),
    ]

    operations = [
        migrations.AddField(
            model_name='controllercomponenttype',
            name='created_by',
            field=models.ForeignKey(help_text='The user that created the type. Global types have no owner.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='controllerauthtoken',
            name='key',
            field=models.CharField(default=iot.models.controller._generate_auth_token, max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='siteentity',
            name='site',
            field=models.ForeignKey(help_text='The site to which the site entity belongs.', on_delete=django.db.models.deletion.CASCADE, related_name='site_entity', to='iot.site'),
        ),
    ]
