# Generated by Django 3.1.7 on 2021-03-17 16:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('iot', '0004_auto_20210313_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapointtype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='The user that created the type. Global types have no owner.', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
