# Generated by Django 3.1.8 on 2021-04-16 13:47

from django.db import migrations, models
import iot.models.data_point


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0005_datapointtype_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datapoint',
            name='time',
            field=models.DateTimeField(default=iot.models.data_point.timezone_aware_now, primary_key=True, serialize=False),
        ),
    ]
