# Generated by Django 3.1.10 on 2021-05-06 19:04

from django.db import migrations, models
import iot.models.firmware_images
import iot.storage_backends
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('iot', '0006_auto_20210416_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='FirmwareImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='The name of the firmware excluding version number.', max_length=255)),
                ('version', models.CharField(help_text='The semantic version of the image.', max_length=255)),
                ('file', models.FileField(help_text='The file of the firmware image.', storage=iot.storage_backends.PrivateMediaStorage, upload_to=iot.models.firmware_images.FirmwareImageManager.generate_path)),
                ('hash_sha3_512', models.BinaryField(help_text='The sha3-512 hash of the uploaded file.', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='The datetime of creation.')),
                ('modified_at', models.DateTimeField(auto_now=True, help_text='The datetime of the last update.')),
            ],
            options={
                'unique_together': {('name', 'version')},
            },
        ),
    ]
